# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_ID }}/ms-shop:latest .
      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_ID }}/ms-shop:latest
      - name: Deploy
        run: |
          gcloud run deploy ms-shop \
          --region us-east1 \
          --image gcr.io/${{ secrets.GCP_ID }}/ms-shop \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_ID }}
